# Configure LGTM for this package

extraction:
  python:
    python_setup:
      version: 3
path_classifiers:
  library:
#    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
    - devtools/*
    - qcdb/legacy/*  # not going to be modified
#  generated:
#    - nist_data/*
#    - qcelemental/_version.py
#queries:
#- exclude:
#    - py/not-named-self # Blocks Pydantic's @validator not accepting `self` until a better fix can be found
#    - py/missing-equals # Blocks Pydantic's equivalent decorator
