# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:

  - os: linux
    env:
      - PYTHON_VER='3.6'

  - os: linux
    env:
      - PYTHON_VER='3.7'

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

  # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Create test environment for package
  - |
    if [ $PROG == "MINIMAL" ]; then
      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/minimal.yaml
    elif [ $PROG == "FULL" ]; then
      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/base.yaml
    else
      echo "ERROR: No match for PROG ($PROG)."
      exit 1
    fi
  - source activate test

before_script:
  - python -V
  - conda list
  - cd ${TRAVIS_BUILD_DIR}
  - > 
      cmake -Bbuild -H. 
      -DCMAKE_BUILD_TYPE=Release
      -DPYTHON_EXECUTABLE="${HOME}/miniconda/envs/test/bin/python"
      -DCMAKE_INSTALL_PREFIX=${HOME}/qcdb-install
  - cd build
  - make -j2
  - make install

script:
  - cd ${HOME}/qcdb-install && PYTHONPATH=lib/ python -m pytest -rws -v --capture=sys --cov

notifications:
    email: false

after_success:
  - codecov
